version: 2.1

# Définir les orbs
orbs:
  codecov: codecov/codecov@4.0.1

# Définir un job pour compiler et tester l'application
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0  # Utilisation d'une image Docker CircleCI OpenJDK
      - image: cimg/base:stable  # Image avec Git et des outils de base
    steps:
      - checkout  # Récupérer le code
      - run:
          name: Build
          command: mvn -B -DskipTests clean package  # Nettoyer et construire sans exécuter les tests
      - run:
          name: Test
          command: mvn test  # Exécuter les tests
      - run:
          name: Jacoco file generation
          command: mvn jacoco:report
      - codecov/upload: # Utilisation de l'orb Codecov pour télécharger les résultats de couverture
          file: target/site/jacoco/jacoco.xml
      - run:
          name: Générer le rapport Checkstyle
          command: |
            mvn checkstyle:checkstyle site
            ls -l target/site  # Liste les fichiers pour vérifier la présence du rapport
      - run:
          name: Déployer sur GitHub Pages
          command: |
            ls
            git config --global "user.name" "SwanNOBILI"
            git config --global "user.email" "nobili.swan@gmail.com"
            git fetch --all
            git checkout gh-pages
            mkdir -p checkstyle
            cp /target/site/checkstyle.html checkstyle/index.html
            git add checkstyle
            git commit -m "Mise à jour du rapport Checkstyle"
            git push origin gh-pages


# Workflow pour orchestrer les jobs
workflows:
  version: 2
  build-and-upload:
    jobs:
      - build-and-test  # Exécuter d'abord le job de construction et tests